In [1]:
age = 36
txt = f"My name is John, I am {age}"
print(txt)

txt2 = f"My name is John. I am {age:.2f}"
print(txt2)

My name is John, I am 36
My name is John. I am 36.00


In [2]:
price = 59
txt = f"The price is {price:.2f} dollars"
print(txt)

The price is 59.00 dollars


In [3]:
txt = "We are the so-called \"Vikings\" from the north"
print(txt)

We are the so-called "Vikings" from the north


In [4]:
txt = "banana"

x = txt.center(20, "0")
print(x)

0000000banana0000000


In [5]:
len(x)

20

In [6]:
txt = "Hello, welcome to my world."

x = txt.find("welcome")

print(x)

7


In [7]:
txt = "Hello, welcome to my world."

x = txt.find("e")

print(x)

1


In [8]:
txt = "THIS IS NOW!"
x = txt.isupper()
print(x)

True


In [9]:
txt = "     banana     "
x = txt
print("of all fruits", x, "is my favorite")
x = txt.lstrip()
print("of all fruits", x, "is my favorite")
x = txt.rstrip()
print("of all fruits", x, "is my favorite")

of all fruits      banana      is my favorite
of all fruits banana      is my favorite
of all fruits      banana is my favorite


In [10]:
txt = "Hello Sam!"

mytable = str.maketrans("S", "P")

print(txt.translate(mytable))


Hello Pam!


In [11]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [12]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])

Ford


In [13]:
car = {
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
}

x = car.keys()

print(x)

car["color"] = "white"

print(x)

dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])


In [14]:
thisdict = {
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
}
x = thisdict.values()

print(x)

dict_values(['Ford', 'Mustang', 1964])


In [15]:
thisdict = {
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
}

x = thisdict.items()

print(x)

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])


In [16]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

John
36


In [17]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("Tobias", 25)

del p1.age

print(p1.name)

Tobias


In [18]:
class Person:
  def __init__(self, name):
    self.name = name

  def greet(self):
    print("Hello, my name is " + self.name)

p1 = Person("Emil")
p1.greet()

Hello, my name is Emil


In [19]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

x = Person("John", "Doe")
x.printname()

John Doe


In [20]:
class Student(Person):
  pass

In [21]:
x = Student("Mike", "Olsen")
x.printname()

Mike Olsen


In [22]:
class Student(Person):
  def __init__(self, fname, lname):
    Person.__init__(self, fname, lname)

In [24]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [25]:
import numpy as np

# arr = np.array([1,2,3])
# print(arr)
# print(type(arr))

arr0 = np.array(100)
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [26]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [27]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [28]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [29]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [30]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [31]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [32]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [33]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [38]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1, 1:4])

[7 8 9]


In [39]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [40]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [41]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr.dtype)

int64


In [42]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [43]:
import numpy as np

arr = np.array([1,2,3,4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [44]:
import numpy as np

arr = np.array([1,2,3,4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32
